version: '1'
services:
  DemoDocker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  backend:
    driver: bridge